---
- name: Install tis wapt repo².
  template:
    src: templates/wapt.j2
    dest: /etc/yum.repos.d/wapt.repo
    owner: root
    group: root
    backup: no
    mode: 0644

- name: yum update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  tags:
    - yum_update

- name: "Install postgresql-{{ pgsql_version }}"
  yum:
    name: [ 'postgresql96-server', 'postgresql96-contrib', 'cabextract' ]
    state: latest

- name: "install tis-waptserver {{ wapt_version }} packages"
  yum:
    name: [ 'tis-waptserver', 'tis-waptsetup' ]
    state: latest

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: initialize postgresql db
  shell: "sudo {{ postgresql_bin_path }}/postgresql96-setup initdb"
  when: not pgdata_dir_version.stat.exists
  args:
    warn: false

- name: start WAPT server services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "postgresql-{{ pgsql_version }}"
    - waptserver
    - nginx
